apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-efs
  labels:
     pv: nfs-pv01
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /cluster/3scale 
    server: fs-0a8ada2b.efs.ap-northeast-1.amazonaws.com
  persistentVolumeReclaimPolicy: Recycle